language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-dev --verbose"

script:
  - phpunit -c phpunit.xml.dist testes/cash-machine
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="244840f9533ff5dc774c5d66fcfbcf96eed850266cd49209bdfa3df502523447" --format=php-clover build/logs/coverage.clover
